[build]
  functions = "functions"
  publish = "public"

[dev]
  functions = "functions"
  publish = "public"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200